# Generated by Django 2.2.5 on 2019-09-22 17:43
import os
from django.db import migrations
from django.contrib.auth import get_user_model


def create_superuser(apps, schema_editor):
    username = os.environ["EXPUNGER_USER"]
    password = os.environ["EXPUNGER_PASS"]

    User = get_user_model()
    root = User.objects.create_user(username, None, password)
    root.is_staff = True
    root.is_superuser = True
    root.save()


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    for name in ["Attorney", "Intern", "Volunteer"]:
        g = Group(name=name)
        g.save()


class Migration(migrations.Migration):
    """
    Build the three initial groups
    """
    dependencies = [
        ('auth', '0011_update_proxy_permissions')
    ]

    operations = [
        migrations.RunPython(create_groups),
        migrations.RunPython(create_superuser)
    ]
